### ISSUE TITLE
How to run the example

### ISSUE THREAD

**Issue by zume2020** [awslabs/aws-lex-browser-audio-capture#21]
I tried to run the example by `node renderer.js ` but it returns this error,

> aws-lex-browser-audio-capture-master\example\renderer.js:3
>   var canvas = document.querySelector('.visualizer');
>                ^
> 
> ReferenceError: document is not defined
>     at D:\ralfe-speech\aws-lex-browser-audio-capture-master\example\renderer.js:3:16
>     at Object.<anonymous> (D:\ralfe-speech\aws-lex-browser-audio-capture-master\example\renderer.js:81:3)
> [90m    at Module._compile (internal/modules/cjs/loader.js:959:30)[39m
> [90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)[39m
> [90m    at Module.load (internal/modules/cjs/loader.js:815:32)[39m
> [90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)[39m
> [90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)[39m
> [90m    at internal/main/run_main_module.js:17:11[39m

I'm running the script on Win10, v12.14.0 ,

**Comment by hectorfloresflores** [comment]
Hi, did you figure out how to do it?

**Comment by hectorfloresflores** [comment]
I was able to make it run, here it is my setup.
1.- run in terminal: npm install
2.- I have AWS for students so in order to work for me I had to add the session token here:
  AWS.config.credentials = new AWS.Credentials(document.getElementById('ACCESS_ID').value, document.getElementById('SECRET_KEY').value,
            'hardcode_here_your_session_token');

And just open index.html in your web browser and thats it!.


NOTE: If you have a normal account you do not have to do anything else, just step 1 and open index.html in web browser.
HAPPY CODING 👍

**Comment by zume2020** [comment]
> I was able to make it run, here it is my setup.
> 1.- run in terminal: npm install
> 2.- I have AWS for students so in order to work for me I had to add the session token here:
> AWS.config.credentials = new AWS.Credentials(document.getElementById('ACCESS_ID').value, document.getElementById('SECRET_KEY').value,
> 'hardcode_here_your_session_token');
> 
> And just open index.html in your web browser and thats it!.
> 
> NOTE: If you have a normal account you do not have to do anything else, just step 1 and open index.html in web browser.
> HAPPY CODING

Happy to know that you fixed it!! 
NB: I even don't remember this thing :sweat_smile:
